server:
  port: 8080
spring:
  application:
    name: "AutenticacionService"
  devtools:
    add-properties: false
  sql:
    init:
      mode: always
  profiles:
    include: null
springdoc:
  paths-to-match: /api/**
adapters:
  driven:
    r2dbc:
      host: localhost
      port: 5432
      database: crediya_auth_db
      username: rponce
      password:
      schema: public
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: "EsteEsUnSecretoSuperLargoYComplejoParaCrediYaQueDebeSerCambiadoEnProduccion12345"
  expiration-ms: 3600000
